apps/realtime/urls.py
from django.urls import include, path

from . import views
from .apis import (AvailableDevicesAPI, AvailableSimCardsAPI,
                   ExportDataAssetsGroups, ExportDataDevices,
                   ExportDataGeofence, ExportDataPlans,
                   ExportDataResponseCommands, ExportDataSendCommands,
                   ExportDataSimcards, ExportDataVehicles, SearchDataPlan,
                   SearchDevices, SearchGeofence, SearchGroupAssets,
                   SearchResponseCommand, SearchSendCommand, SearchSimcards,
                   SearchVehicles, get_brands, get_commands,
                   get_company_id_items_report, get_data_plans, get_lines,
                   list_family_model, list_manufacture)

app_name = "realtime"

urlpatterns = [
    # Configuración y reportes
    path(
        "configuration-report/",
        views.ConfigurationReportView.as_view(),
        name="add_configuration_report",
    ),
    # Otras URLs
    path("get-instance-data/", get_company_id_items_report, name="get_instance_data"),
    path(
        "configuration-report/update/<int:company_id>/",
        views.UpdateConfigurationReportView.as_view(),
        name="update_configuration_report",
    ),
    # Dispositivos
    path(
        "devices/",
        include(
            [
                path("", views.ListDeviceTemplate.as_view(), name="devices"),
                path("add_device", views.AddDeviceView.as_view(), name="add_device"),
                path(
                    "update_device/<str:pk>",
                    views.UpdateDeviceView.as_view(),
                    name="update_device",
                ),
                path(
                    "delete/<str:pk>",
                    views.DeleteDeviceView.as_view(),
                    name="delete_device",
                ),
                path(
                    "api/available-simcards/<int:company_id>/",
                    AvailableSimCardsAPI.as_view(),
                    name="available-simcards",
                ),
                path(
                    "api/available-simcards/<int:company_id>/<str:imei>/",
                    AvailableSimCardsAPI.as_view(),
                    name="available-simcards-edit",
                ),
                path(
                    "api/family_model/<int:manufacture_id>/",
                    list_family_model,
                    name="family",
                ),
                path(
                    "api/manufacture/<int:family_model_id>/",
                    list_manufacture,
                    name="manufacture",
                ),
                # API para traer info de devices + search
                path("devices-user", SearchDevices.as_view(), name="devices_user"),
                path("devices-export", ExportDataDevices.as_view(), name="devices_export"),
            ]
        ),
    ),
    # Vehículos
    path(
        "vehicles/",
        include(
            [
                path("", views.ListVehicleTemplate.as_view(), name="vehicles"),
                path("add_vehicle", views.AddVehicleView.as_view(), name="add_vehicle"),
                path("get_brands/", get_brands, name="get_brands"),
                path("get_lines/", get_lines, name="get_lines"),
                path(
                    "update_vehicle/<int:pk>",
                    views.UpdateVehicleView.as_view(),
                    name="update_vehicle",
                ),
                path(
                    "delete/<int:pk>",
                    views.DeleteVehicleView.as_view(),
                    name="delete_vehicle",
                ),
                path(
                    "api/available-devices/<int:company_id>/",
                    AvailableDevicesAPI.as_view(),
                    name="available-devices",
                ),
                path(
                    "api/available-devices/<int:company_id>/<int:vehicle_id>/",
                    AvailableDevicesAPI.as_view(),
                    name="available-devices-edit",
                ),
                # API para traer info de vehiculos+ search
                path("vehicles-user", SearchVehicles.as_view(), name="vehicles_user"),
                path("assets-export", ExportDataVehicles.as_view(), name="assets_export"),
            ]
        ),
    ),
    # Grupos de vehículos
    path(
        "group_vehicles/",
        include(
            [
                path(
                    "", views.ListVehicleGroupTemplate.as_view(), name="group_vehicles"
                ),
                path(
                    "add_group",
                    views.AddVehicleGroupView.as_view(),
                    name="add_group_vehicle",
                ),
                path(
                    "update_group/<int:pk>",
                    views.UpdateVehicleGroupView.as_view(),
                    name="update_group_vehicle",
                ),
                path(
                    "delete_group/<int:pk>",
                    views.DeleteVehicleGroupView.as_view(),
                    name="delete_group_vehicle",
                ),
                path("group-assets", SearchGroupAssets.as_view(), name="assets_group"),
                path("export-group-assets", ExportDataAssetsGroups.as_view(), name="export_assets_group"),
            ]
        ),
    ),
    # Simcards
    path(
        "simcards/",
        include(
            [
                path("", views.ListSimcardTemplate.as_view(), name="simcards"),
                path("add", views.AddSimcardView.as_view(), name="add_simcard"),
                path(
                    "update/<int:pk>",
                    views.UpdateSimcardView.as_view(),
                    name="update_simcard",
                ),
                path(
                    "delete/<int:pk>",
                    views.DeleteSimcardView.as_view(),
                    name="delete_simcard",
                ),
                path(
                    "api/data-plans/<int:company_id>/",
                    get_data_plans,
                    name="get_data_plans",
                ),
                # API para traer info de simcards + search
                path("simcards-user", SearchSimcards.as_view(), name="simcards_user"),
                path("simcards-export", ExportDataSimcards.as_view(), name="simcards_export"),
            ]
        ),
    ),
    # DataPlan
    path(
        "dataplan/",
        include(
            [
                path("", views.ListDataPlanTemplate.as_view(), name="dataplan"),
                path("add", views.AddDataPlanView.as_view(), name="add_data_plan"),
                path(
                    "update_plan/<int:pk>",
                    views.UpdateDataPlanView.as_view(),
                    name="update_data_plan",
                ),
                path(
                    "delete/<int:pk>",
                    views.DeleteDataPlanView.as_view(),
                    name="delete_data_plan",
                ),
                # API para traer info de planes de datos + search
                path("dataplan-user", SearchDataPlan.as_view(), name="dataplan_user"),
                path("dataplan-export", ExportDataPlans.as_view(), name="dataplan_export"),
            ]
        ),
    ),
    # Comandos
    path(
        "commands/",
        include(
            [
                path("", views.ListSendingCommandsTemplate.as_view(), name="commands"),
                path(
                    "add", views.AddSendingCommandsView.as_view(), name="add_Commands"
                ),
                path(
                    "response",
                    views.ListResponseCommandsTemplate.as_view(),
                    name="response_commands",
                ),
                path("get-commands/<str:imei>/", get_commands, name="get_commands"),
                #API para traer info de planes de comandos enviados + search
                path("send-commands", SearchSendCommand.as_view(), name="send_commands"),
                path("response-commands", SearchResponseCommand.as_view(), name="commands_response"),
                path("export-commands", ExportDataSendCommands.as_view(), name="export_commands"),
                path("export-response-commands", ExportDataResponseCommands.as_view(), name="export_responsecommands"),
                
            ]
        ),
    ),
    # Geozonas
    path(
        "geozones/",
        include(
            [
                path("", views.ListGeozonesTemplate.as_view(), name="geozones"),
                path(
                    "add_geozones", views.AddGeozonesView.as_view(), name="add_geozones"
                ),
                path(
                    "delete/<int:pk>",
                    views.DeleteGeozonesView.as_view(),
                    name="delete_geozones",
                ),
                path("geofence-user", SearchGeofence.as_view(), name="geofence_user"),
                path("geofence-export", ExportDataGeofence.as_view(), name="geofence_export"),
            ]
        ),
    ),
]

config/urls.py
"""
Configuración de URLs.

La lista `urlpatterns` contiene las direcciones URL de las vistas. Para más detalles, consulte:
https://docs.djangoproject.com/en/4.1/topics/http/urls/
"""

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

apps = i18n_patterns(
    # Módulo personalizado de autenticación de usuarios.
    path("", include("apps.authentication.urls"), name="main"),
    # Métodos de autenticación de Django. El módulo `authentication` los reescribe.
    path("", include("django.contrib.auth.urls")),
    # Módulo de puntos de control (checkpoints).
    path("checkpoints/", include("apps.checkpoints.urls")),
    # Módulo de eventos
    path("events/", include("apps.events.urls")),
    # Módulo de reporte en tiempo real (realtime).
    path("realtime/", include("apps.realtime.urls")),
    # Módulo para la administración, personalización y creación de empresas (whitelabel).
    path("whitelabel/", include("apps.whitelabel.urls")),
    # Modulo de socketmap
    path("socketmap/", include("apps.socketmap.urls")),
    # Modulo de Power BI Embbeded
    path("powerbi/", include("apps.powerbi.urls")),
)

django = i18n_patterns(
    # Sitio de administración de Django.
    path("admin/", admin.site.urls),
    # Librería de control de traducciones
    path("rosetta/", include("rosetta.urls")),
)


media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

static_files = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns = apps + django + media + static_files

apps/templates/realtime/group_vehicles/add_group_vehicles.html
{% load i18n static %} {% block content %} {{form.media}}
<div class="modal-content">
  <div class="modal-body">
    <div class="card">
    <div class="modal-header">
      <h3>{% trans "Add Group" %}</h3>
      <button type="button" id="cerrarVenta" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="card-body">
      <form hx-post="{{ request.path }}" hx-target="#modal-content" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="col">
            <p></p>
            <div class="input-group input-group-static mb-4">
              <label for="id_plate"
                >{% trans "Name group" %}<span style="color: red">
                  *</span
                ></label
              >
              {{form.name}}
            </div>
          </div>
          <div class="col">
            <p></p>
            <label for="{{ form.vehicles.auto_id }}">{% trans "Assets:" %}<span style="color: red"> *</span
              ></label>
              <div class="input-group input-group-outline">
                <input
                  id="search-assets"
                  type="text"
                  class="form-control"
                  placeholder={% trans "Search" %}
                  onfocus="focused(this)"
                  onfocusout="defocused(this)"
                  autocomplete="off"
                />
              </div>
            <div class="scroll">
              <label class="form-check-label vehicles" for>
                {{ form.vehicles }}
              </label>
            </div>
            {% if form.vehicles.errors %}
                  <div class="mt-2" style="color: red;">
                    {% for error in form.vehicles.errors %}
                      <div>{{ error }}</div>
                    {% endfor %}
                  </div>
                {% endif %}
          </div>
        </div>
        <div class="row">
          <div class="col">
            <button class="btn btn-primary mt-3" type="submit">
              <i class="fa-solid fa-floppy-disk me-2"></i> {% trans "Save" %}
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<head>
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/estilos_templates.css' %}">
</head>
<script>
  function filterOptions(searchInputId, optionsContainerClass) {
    var searchInput = document.getElementById(searchInputId);
    searchInput.addEventListener("keyup", function (event) {
      var query = event.target.value.toLowerCase();
      var labels = document.querySelectorAll("." + optionsContainerClass + " label");
      labels.forEach(function (label) {
        label.style.display = label.textContent.toLowerCase().includes(query) ? "" : "none";
      });
    });
  }

  filterOptions("search-assets", "vehicles");
</script>
{% endblock content %}

apps/templates/realtime/group_vehicles/delete_group_vehicles.html
{% load i18n static %} {% block content %}

<!-- Un formulario que pregunta al usuario si está seguro de querer eliminar la empresa. -->
<div class="modal-content">
  <div class="row">
    <div class="modal-body-md-1">
      <div class="col" >
        <div class="card align-items-center">
          <div class="card-body">
            <form hx-post="{{ request.path }}" hx-target="#modal-content">
              {% csrf_token %}
              <p>{% trans '¿Are you sure you want to delete the Group' %} "{{ object.name}}" ?</p>
              <div class="d-grid col-4 mx-auto">
                <button type="submit" class="btn btn-primary">{% trans "Confirm" %}</button>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">{% trans 'Cancel' %}</button>
              </div>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

apps/templates/realtime/group_vehicles/main_group_vehicles.html
{% extends "layouts/base.html" %}
{% load i18n static %}

{% block title %}
    {% trans "Group Assets" %}
{% endblock %}

{% block content %}
<div class="container-fluid py-4 custom-padding-container" style="overflow: hidden;">
  <div class="row">
    <div class="col-12">
      <div class="card my-4 custom-padding-card-my-4">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
          <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
            <div class="col">
              <h5 class="text-white text-capitalize ps-3">{% trans "Group Assets" %}</h5>
            </div>
          </div>
        </div>
        <div class="card-body custom-padding-body">
            <div class="row align-items-center mb-3">
                    <div class="col-12 d-flex flex-column flex-md-row align-items-center justify-content-between">
                      <div class="d-flex flex-wrap align-items-center mb-2 mb-md-0">
                        <form method="POST" action="{% url 'realtime:group_vehicles' %}" class="d-flex align-items-center">
                            {% csrf_token %}
                            <label class="me-2" style="padding-top: 4px;">{% trans "Show" %}</label>
                            <select name="paginate_by" onchange="this.form.submit()" class="form-select form-select-sm me-2">
                                <option value="15" {% if request.POST.paginate_by == '15' or paginate_by == 15 %} selected {% endif %}>15</option>
                                <option value="25" {% if request.POST.paginate_by == '25' or paginate_by == 25 %} selected {% endif %}>25</option>
                                <option value="50" {% if request.POST.paginate_by == '50' or paginate_by == 50 %} selected {% endif %}>50</option>
                                <option value="100" {% if request.POST.paginate_by == '100' or paginate_by == 100 %} selected {% endif %}>100</option>
                            </select>
                            <label class="mt-1">{% trans "results" %}</label>
                            <input type="hidden" name="q" value="{{ request.POST.q }}">
                        </form>
                    </div>
                    <div class="d-flex justify-content-end align-items-center flex-wrap">
                      {% if perms.realtime.add_vehicle %}
                      <button type="button" hx-get="{% url 'realtime:add_group_vehicle' %}" class="btn btn-primary mx-2" hx-target="#modal .modal-content" style="padding: 9px 12px; margin: 0 0 0 -1px;">
                          <i class="fa-solid fa-plus"></i> {% trans "Add Group" %}
                      </button>
                      {% endif %}
                      {% if object_list %}
                      <a class="btn btn-primary" id="exportExcelBtn" type="button" style="padding: 9px 12px; margin-right: 8px !important; margin: 0 0 0 -1px;">
                          <i class="fa-solid fa-file-excel mx-2"></i> {% trans "Export to Excel" %}
                      </a>
                      {% endif %}
                      <form id="search-form" method="GET" class="flex me-md-3 mb-2 mb-md-0" style="max-width: 180px;" onsubmit="return false">
                          <div class="input-group input-group-sm input-group-outline">
                              <label class="form-label">{% trans "Search..." %}</label>
                              <input id="search-input" type="text" class="form-control" onfocus="focused(this)" onfocusout="defocused(this)" name="q" autocomplete="off">
                          </div>
                      </form>
                    </div>
                </div>
            </div>
            <div style="overflow-x: auto;">
            <div class="table-responsive">
              <table class="table align-items-center mb-0">
                <thead>
                  <tr>
                    <th></th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                      <form id="sort-form-name" method="post" style="display: none;" action="{% url 'realtime:group_vehicles' %}">
                          {% csrf_token %}
                          <input type="hidden" name="order_by" value="name">
                          <input type="hidden" name="direction" value="{% if order_by == 'name' and direction == 'asc' %}desc{% else %}asc{% endif %}">
                      </form>
                      <a href="#" onclick="document.getElementById('sort-form-name').submit(); return false;">
                          {% trans "Name Group" %}
                          <span class="sort-indicator">
                              <span class="sort-arrow sort-arrow-up {% if order_by == 'name' and direction == 'asc' %}active{% else %}inactive{% endif %}">↑</span>
                              <span class="sort-arrow sort-arrow-down {% if order_by == 'name' and direction == 'desc' %}active{% else %}inactive{% endif %}">↓</span>
                          </span>
                      </a>
                    </th>
                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                        <form id="sort-form-vehiclecount" method="post" style="display: none;" action="{% url 'realtime:group_vehicles' %}">
                            {% csrf_token %}
                            <input type="hidden" name="order_by" value="VehicleCount">
                            <input type="hidden" name="direction" value="{% if order_by == 'VehicleCount' and direction == 'asc' %}desc{% else %}asc{% endif %}">
                        </form>
                        <a href="#" onclick="document.getElementById('sort-form-vehiclecount').submit(); return false;">
                            {% trans "Content" %}
                            <span class="sort-indicator">
                                <span class="sort-arrow sort-arrow-up {% if order_by == 'VehicleCount' and direction == 'asc' %}active{% else %}inactive{% endif %}">↑</span>
                                <span class="sort-arrow sort-arrow-down {% if order_by == 'VehicleCount' and direction == 'desc' %}active{% else %}inactive{% endif %}">↓</span>
                            </span>
                        </a>
                    </th>
                  </tr>
                </thead>
                <tbody id="group-tbody">
                  {% for group in group_and_vehicle_count %}
                  <tr>
                    <td class="text-center p-2">
                      {% if perms.realtime.change_vehiclegroup %}
                          <button type="button" hx-get="{% url 'realtime:update_group_vehicle' group.id %}" class="btn btn-primary btn-sm" hx-target="#modal .modal-content">
                              <i class="fa-solid fa-pencil"></i>
                          </button>
                      {% endif %}
                      {% if perms.realtime.delete_vehiclegroup %}
                          <button type="button" hx-get="{% url 'realtime:delete_group_vehicle' group.id %}" class="btn btn-danger btn-sm ml-2" hx-target="#modal .modal-content">
                              <i class="fa-solid fa-trash"></i>
                          </button>
                      {% endif %}
                    </td>
                    <td class="align-middle text-center text-sm">
                      <span class="text-secondary mb-0"> {{ group.name }} </span>
                    </td>
                    <td class="align-middle text-center text-sm">
                      <span class="text-secondary mb-0"> {{ group.VehicleCount }}</span>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          <form id="pagination-form" method="post" action="">
            {% csrf_token %}
            <input type="hidden" name="paginate_by" value="{{ request.POST.paginate_by }}">
            <input type="hidden" name="q" value="{{ request.GET.q }}">
            <input type="hidden" name="page" id="page-input" value="{{ page_obj.number }}">
          </form>
          <div class="row mt-2 custom-row">
            <div class="col-6 d-flex justify-content-start align-items-center">
                <div class="pagination-info">
                    {% trans 'Displaying' %} {{ page_obj.start_index }} {% trans 'to' %} {{ page_obj.end_index }} {% trans 'of' %} {{ page_obj.paginator.count }} {% trans 'items.' %}
                </div>
            </div>
            <div class="col-6 d-flex justify-content-end">
                <nav aria-label="Page navigation" id="pagination-container">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="#" onclick="setPageAndSubmit(1); return false;">
                                    {% trans 'Home' %}
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#" onclick="setPageAndSubmit({{ page_obj.previous_page_number }}); return false;">
                                    &laquo;
                                </a>
                            </li>
                        {% endif %}
                        {% if page_obj.number|add:"-4" > 1 %}
                            <li class="page-item"><span class="page-link">...</span></li>
                        {% endif %}
                        {% for num in page_obj.paginator.page_range %}
                            {% if num > page_obj.number|add:"-4" and num < page_obj.number|add:"4" %}
                                <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                                    <a class="page-link" href="#" onclick="setPageAndSubmit({{ num }}); return false;">
                                        {{ num }}
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.number|add:"3" < page_obj.paginator.num_pages %}
                            <li class="page-item"><span class="page-link">...</span></li>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="#" onclick="setPageAndSubmit({{ page_obj.next_page_number }}); return false;">
                                    &raquo;
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#" onclick="setPageAndSubmit({{ page_obj.paginator.num_pages }}); return false;">
                                    {% trans 'End' %}
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="downloadModal" tabindex="-1" aria-labelledby="downloadModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-start modal-dialog-scrollable" style="max-width: 25%;">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="downloadModalLabel">{% trans "Download Progress" %}</h5>
              <button type="button" id="cerrarVenta" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <div class="progress">
                  <div id="downloadProgressBar" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar">0%</div>
              </div>
          </div>
      </div>
  </div>
</div>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/estilos_templates.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style_main_list.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/report/report_today.css' %}">
  <!-- FontAwesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.3/xlsx.full.min.js"></script>
</head>
<script>
  var csrfToken = "{{ csrf_token }}";
  var permiseChange = "{{ perms.realtime.change_vehiclegroup }}";
  var permiseDelete = "{{ perms.realtime.delete_vehiclegroup }}";
  const updateGroupUrl = "{% url 'realtime:update_group_vehicle' 0 %}";
  const deleteGroupUrl = "{% url 'realtime:delete_group_vehicle' 0 %}";
  var translations = {
      low: "{% trans 'Low' %}",
      medium: "{% trans 'Medium' %}",
      high: "{% trans 'High' %}",
      end: "{% trans 'End' %}",
      home: "{% trans 'Home' %}",
      open: "{% trans 'Open' %}",
      closed: "{% trans 'Closed' %}",
      false: "{% trans 'Inactive' %}",
      true: "{% trans 'Active' %}",
      to: "{% trans 'to' %}",
      of: "{% trans 'of' %}",
      unassigned : "{% trans 'Unassigned' %}",
      displaying: "{% trans 'Displaying' %}",
      assetsGroups: "{% trans 'Assets_Groups' %}",
  };
</script>
<script src="{% static 'assets/js/realtime/group_assets/search_group.js' %}"></script>
<script src="{% static 'assets/js/asc_desc.js' %}"></script>
<script src="{% static 'assets/js/realtime/group_assets/export_excel_assets_groups.js' %}"></script>
{% endblock %}

apps/templates/realtime/group_vehicles/update_group_vehicles.html
{% load i18n static %} {% block content %} {{form.media}}
<div class="modal-content">
  <div class="modal-body">
    <div class="card">
    <div class="modal-header">
      <h3>{% trans "Update Gruop" %}</h3>
      <button type="button" id="cerrarVenta" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="card-body">
      <form hx-post="{{ request.path }}" hx-target="#modal-content" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="col">
            <p></p>
            <div class="input-group input-group-static mb-4">
              <label for="id_plate"
                >{% trans "Name group" %}<span style="color: red">
                  *</span
                ></label
              >
              {{form.name}}
            </div>
          </div>
          <div class="col">
            <p></p>
            <label for="{{ form.vehicles.auto_id }}">{% trans "Assets:" %}<span style="color: red"> *</span
              ></label>
              <div class="input-group input-group-outline">
                <input
                  id="search-assets"
                  type="text"
                  class="form-control"
                  placeholder={% trans "Search" %}
                  onfocus="focused(this)"
                  onfocusout="defocused(this)"
                  autocomplete="off"
                />
              </div>
              <div class="scroll">
                <label class="form-check-label vehicles" for>
                  {{ form.vehicles }}
                </label>
              </div>
              {% if form.vehicles.errors %}
                  <div class="mt-2" style="color: red;">
                    {% for error in form.vehicles.errors %}
                      <div>{{ error }}</div>
                    {% endfor %}
                  </div>
                {% endif %}
            </div>
          </div>
          <div class="row">
            <div class="col">
              <button class="btn btn-primary mt-3" type="submit">
                <i class="fa-solid fa-floppy-disk me-2"></i> {% trans "Save" %}
              </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/estilos_templates.css' %}">
</head>
<script>
  function filterOptions(searchInputId, optionsContainerClass) {
    var searchInput = document.getElementById(searchInputId);
    searchInput.addEventListener("keyup", function (event) {
      var query = event.target.value.toLowerCase();
      var labels = document.querySelectorAll("." + optionsContainerClass + " label");
      labels.forEach(function (label) {
        label.style.display = label.textContent.toLowerCase().includes(query) ? "" : "none";
      });
    });
  }

  filterOptions("search-assets", "vehicles");
</script>
{% endblock content %}