apps/checkpoints/urls.py
from django.urls import include, path

from apps.checkpoints.sql import fetch_all_confidatasem

from . import views
from .api import (ExportDataDriver, ExportDataScoreDriver, SearchDataSem,
                  SearchDrivers, SearchScores, events_by_company,
                  events_person_by_company, export_report, user_by_company,
                  vehicles_by_company)

app_name = "checkpoints"

urlpatterns = [
    # Conductores y su manejo
    path(
        "drivers/",
        include(
            [
                path("", views.ListDriverTemplate.as_view(), name="list_drivers"),
                path("add", views.AddDriverView.as_view(), name="add_driver"),
                path(
                    "update/<int:pk>",
                    views.UpdateDriverView.as_view(),
                    name="update_driver",
                ),
                path(
                    "delete/<int:pk>",
                    views.DeleteDriverView.as_view(),
                    name="delete_driver",
                ),
                path(
                    "assign_driver/<int:pk>",
                    views.AddAssignDriverView.as_view(),
                    name="assign_driver",
                ),
                path(
                    "update_assign/<int:pk>",
                    views.UpdateAssignDriverView.as_view(),
                    name="update_assign",
                ),
                path("assign/<int:pk>", views.BottonView.as_view(), name="button_view"),
                path(
                    "update_assing_vehicle/<int:pk>",
                    views.UpdateVehicleAssignView.as_view(),
                    name="update_vehicle_assign",
                ),
                path("drivers-user", SearchDrivers.as_view(), name="user_driver"),
                path("export-drivers", ExportDataDriver.as_view(), name="export_drivers"),
            ]
        ),
    ),
    # Calificación de conductores
    path(
        "driver/",
        include(
            [
                path(
                    "list_score_configuration/",
                    views.ListScoreCompanyTemplate.as_view(),
                    name="list_score_configuration",
                ),
                path(
                    "score_configuration/<int:pk>",
                    views.ScoreConfigurationView.as_view(),
                    name="score_configuration",
                ),
                path("scores-user", SearchScores.as_view(), name="user_scores"),
                path("export-scores", ExportDataScoreDriver.as_view(), name="export_scores"),
            ]
        ),
    ),
    # Reportes
    path(
        "reports/",
        include(
            [
                path("driver", views.ReporDriverView.as_view(), name="report_driver"),
                path("today/", views.ReportTodayView.as_view(), name="report_today"),
                # traer vehicle por compañia
                path(
                    "vehicles-by-company/<int:company_id>/",
                    vehicles_by_company,
                    name="vehicles_by_company",
                ),
                # traer eventos por compañia
                path(
                    "events-by-company/<int:company_id>/",
                    events_by_company,
                    name="events_by_company",
                ),
                path(
                    "events_person-by-company/<int:company_id>/",
                    events_person_by_company,
                    name="events_by_company",
                ),
                path("avldat", export_report, name="avldat"),
                
            ]
        ),
    ),
    path(
        "powerbi/",
        include(
            [
                path(
                    "DataSeM",
                    views.Advanced_AnalyticalView.as_view(),
                    name="DataSeM",
                ),
                path(
                    "Confi_DataSeM",
                    views.DataSemConfigurationList.as_view(),
                    name="Config_DataSeM",
                ),
                path(
                    "DataSeM/Add",
                    views.AddDataSemConfiguration.as_view(),
                    name="AddDataSeM",
                ),
                path(
                    "DataSeM/Update/<int:pk>/",
                    views.UpdateDataSemConfiguration.as_view(),
                    name="UpdateDataSeM",
                ),
                path(
                    "DataSeM/Delete/<int:pk>/",
                    views.DeleteDataSemConfiguration.as_view(),
                    name="DeleteDataSeM",
                ),
                path("search_datasem", SearchDataSem.as_view(), name="search_datasem"),
                path("user_company/<int:company_id>/", user_by_company , name="list_user"),
            ]
        ),
    ),
]

config/urls.py
"""
Configuración de URLs.

La lista `urlpatterns` contiene las direcciones URL de las vistas. Para más detalles, consulte:
https://docs.djangoproject.com/en/4.1/topics/http/urls/
"""

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

apps = i18n_patterns(
    # Módulo personalizado de autenticación de usuarios.
    path("", include("apps.authentication.urls"), name="main"),
    # Métodos de autenticación de Django. El módulo `authentication` los reescribe.
    path("", include("django.contrib.auth.urls")),
    # Módulo de puntos de control (checkpoints).
    path("checkpoints/", include("apps.checkpoints.urls")),
    # Módulo de eventos
    path("events/", include("apps.events.urls")),
    # Módulo de reporte en tiempo real (realtime).
    path("realtime/", include("apps.realtime.urls")),
    # Módulo para la administración, personalización y creación de empresas (whitelabel).
    path("whitelabel/", include("apps.whitelabel.urls")),
    # Modulo de socketmap
    path("socketmap/", include("apps.socketmap.urls")),
    # Modulo de Power BI Embbeded
    path("powerbi/", include("apps.powerbi.urls")),
)

django = i18n_patterns(
    # Sitio de administración de Django.
    path("admin/", admin.site.urls),
    # Librería de control de traducciones
    path("rosetta/", include("rosetta.urls")),
)


media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

static_files = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns = apps + django + media + static_files

apps/checkpoints/models.py
""" Modelos asociados al módulo puntos de control.

Este módulo crea los modelos para los puntos de control, las rutas, el control de fatiga y los
datos para análisis de los conductores.

Para una mayor referencia sobre la creación de modelos en Django, consulte
https://docs.djangoproject.com/en/4.1/topics/db/models/
"""

from django.db import models
from django.utils.translation import gettext_lazy as _


class Driver(models.Model):
    """
    Modelo de la tabla driver. Almacena la información asociada a cada conductor
    de la empresa cliente.
    """

    company = models.ForeignKey(
        "whitelabel.Company",
        on_delete=models.CASCADE,
        verbose_name=_("company"),
        default=1,
    )
    last_update = models.DateTimeField(
        verbose_name=_("last update"),
        auto_now=True,
    )
    personal_identification_number = models.PositiveBigIntegerField(
        verbose_name=_("personal ID"),
        null=False,
        blank=False,
    )
    first_name = models.CharField(
        max_length=30,
        verbose_name=_("first name"),
        default="",
    )
    last_name = models.CharField(
        max_length=30,
        verbose_name=_("last name"),
        default="",
    )
    address = models.CharField(
        max_length=30,
        verbose_name=_("address"),
        default="",
        blank=True,
    )
    phone_number = models.PositiveBigIntegerField(
        verbose_name=_("movil number"),
        default="",
    )
    password = models.CharField(
        max_length=10,
        verbose_name=_("password"),
        default="",
        null=True,
    )
    date_joined = models.DateField(verbose_name=_("date joined"))
    is_active = models.BooleanField(default=False, verbose_name=_("Active"))
    visible = models.BooleanField(default=True, verbose_name=_("visible"))
    modified_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("modified by"),
        related_name="modified_driver",
        null=True,
    )

    created_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("created by"),
        related_name="created_driver",
        null=True,
    )

    def __str__(self):
        return f"{self.first_name}   {self.last_name}"


class DriverAnalytic(models.Model):
    """
    Modelo de la tabla driver_analytic. Almacena la información asociada a la asignación
    y desasignación de conductores a vehiculos.
    """

    vehicle = models.ForeignKey(
        "realtime.Vehicle",
        on_delete=models.CASCADE,
        verbose_name=_("vehicle"),
        null=True,
    )
    driver = models.ForeignKey(
        "Driver", on_delete=models.CASCADE, verbose_name=_("driver"), null=True
    )
    date_joined = models.DateTimeField(
        verbose_name=_("date joined"),
        null=True,
    )
    date_leaving = models.DateTimeField(
        verbose_name=_("date leaving"),
        blank=True,
        null=True,
    )
    modified_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("modified by"),
        related_name="modified_driver_analytic",
        null=True,
    )
    created_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("created by"),
        related_name="created_driver_analytic",
        null=True,
    )
    last_update = models.DateTimeField(
        verbose_name=_("last update"),
        auto_now=True,
    )

    def __str__(self):
        return f"{self.vehicle} --> Driver: {self.driver}"


class ItemScore(models.Model):
    """
    Modelo de la tabla item_score. Almacena los items predefinidos sobre los cuales
    se califica a los conductores.
    """

    item = models.CharField(
        verbose_name=_("item"),
        max_length=50,
    )
    modified_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("modified by"),
        related_name="modified_items",
        null=True,
    )
    created_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("created by"),
        related_name="created_items",
        null=True,
    )
    last_updated = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("last updated"),
        null=True,
    )

    def __str__(self):
        return f"{self.item}"


class CompanyScoreSetup(models.Model):
    """
    Modelo de la tabla company_score_setup Almacena el puntaje que cada empresa
    establece para calificar a sus conductores.
    """

    company = models.ForeignKey(
        "whitelabel.Company",
        on_delete=models.CASCADE,
        verbose_name=_("company"),
        null=True,
    )
    min_score = models.FloatField(
        verbose_name=_("minimum score"),
        blank=True,
        default=0,
    )
    max_score = models.FloatField(
        verbose_name=_("maximum score"),
        blank=True,
        default=0,
    )
    cotoff_date = models.IntegerField(
        verbose_name=_("cutoff date"),
        default=1,
        choices=[(day, day) for day in range(1, 31)],
    )
    modified_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("modified by"),
        related_name="modified_Companyscoresetup",
        null=True,
    )
    created_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("created by"),
        related_name="created_companyscoresetup",
        null=True,
    )
    last_update = models.DateTimeField(
        verbose_name=_("last update"),
        auto_now=True,
    )

    def __str__(self):
        return f" {self.company} --> Score: [ {self.min_score} , {self.max_score},{self.cotoff_date}]"


class ItemScoreSetup(models.Model):
    """
    Modelo de la tabla item_score_setup. Almacena el porcentaje que representa en la nota total
    cada item a evaluar.
    """

    item = models.ForeignKey(
        "ItemScore",
        on_delete=models.CASCADE,
        verbose_name=_("item"),
        default=1,
    )
    company_score = models.ForeignKey(
        "CompanyScoreSetup",
        on_delete=models.CASCADE,
        verbose_name=_("company score"),
        null=True,
    )
    points_item_score = models.FloatField(
        verbose_name=_("points score item"),
        blank=True,
        default=0,
    )
    maximum_infractions = models.IntegerField(
        verbose_name=_("maximum infractions"),
        blank=True,
        default=0,
    )
    subtract_points = models.FloatField(
        verbose_name=_("subtract points"),
        blank=True,
        default=0,
    )
    modified_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("modified by"),
        related_name="modified_itemsscoresetup",
        null=True,
    )
    created_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("created by"),
        related_name="created_itemsscoresetup",
        null=True,
    )
    last_update = models.DateTimeField(
        verbose_name=_("last update"),
        auto_now=True,
    )

    def __str__(self):
        return f" {self.company_score}---{self.item} --> Percentage:[ {self.points_item_score}] -- "


class FatigueControl(models.Model):

    """
    Modelo de el cual realiza el calculo de la calificacion del conductor con el modelo DriverAnalytic
    de acuerdo a los parametros que se hayan establecido en el modelo ItemScoreSetup y se valida
    de acuerdo a la información que envie el divice al modelo Avldata
    """

    driver = models.ForeignKey(
        "DriverAnalytic", on_delete=models.CASCADE, verbose_name=_("Driver"), null=True
    )
    items_score = models.ForeignKey(
        "ItemScoreSetup",
        on_delete=models.CASCADE,
        verbose_name=_("Items_score"),
        null=True,
    )
    avl_data = models.ForeignKey(
        "realtime.AVLData",
        on_delete=models.CASCADE,
        verbose_name=_("AVLData"),
        null=True,
    )
    vehicle = models.ForeignKey(
        "realtime.Vehicle",
        on_delete=models.CASCADE,
        verbose_name=_("Vehicle"),
        default=None,
    )

    def __str__(self):
        return f" {self.driver} --> {self.items_score} --> {self.avl_data}"


class Report(models.Model):
    # No necesitas definir permisos en la clase Meta para los permisos básicos
    class Meta:
        verbose_name_plural = "reports"


class Advanced_Analytical(models.Model):
    user = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("user"),
        null=True,
    )
    id_workspace = models.CharField(
        max_length=50,
        verbose_name=_("ID Workspace"),
    )

    id_report = models.CharField(
        max_length=30,
        verbose_name=_("id_report"),
    )
    workspace = models.CharField(
        max_length=30,
        verbose_name=_("workspace"),
    )
    report = models.CharField(
        max_length=30,
        verbose_name=_("report"),
    )

    coin = models.ForeignKey(
        "whitelabel.Coin",
        on_delete=models.CASCADE,
        verbose_name=_("coin"),
        null=True,
    )
    price = models.DecimalField(
        max_digits=10,  # Ajusta estos valores según tus necesidades
        decimal_places=2,  # Ajusta estos valores según tus necesidades
        verbose_name=_("price"),
        blank=True,
        null=True,
    )
    modified_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("modified by"),
        related_name="modified_advanced_analytic",
        null=True,
    )
    created_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("created by"),

apps/templates/checkpoints/score_configuration/update_score_configuration.html
{% load i18n static %} {% block content %}

{{form.media}}
<div class="modal-content">
    <div class="modal-body">
      <div class="card">
      <div class="modal-header">
                <h3 class="">{% trans "Driver Qualification" %}</h3>
                <button type="button" id="cerrarVenta" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="card-body">
                <form hx-post="{{ request.path }}" hx-target="#modal-content"> {% csrf_token %}
                        <div class=row>
                            <p class="mb-0" align="justify">
                                {% trans "In the Minimum score and Maximum score fields, please indicate the score range with which you wish to rate your drivers. The maximum score is assigned to the best driver." %}
                            </p>
                        </div>
                        <div class=row>
                            <div class=col>
                                <p>
                                <div >
                                    <label for="Company"> {% trans "Company" %} </label>
                                        <h6>{{company.company_name}}</h6>
                                </div>
                            </p>
                            </div>

                            <div class=col>
                                <p>
                                    <div type="date" class="input-group input-group-static mb-4">
                                        <label for="id_min_score"> {% trans "Minimum score" %} </label>
                                        {{form.min_score}}
                                    </div>
                                    <div id="form-errors">
                                        {{form.min_score.errors}}
                                    </div>
                                </p>
                            </div>
                            <div class=col>
                                <p>
                                    <div class="input-group input-group-static mb-4">
                                        <label for="id_max_score"> {% trans "Maximum score" %} </label>
                                        {{form.max_score}}
                                    </div>
                                    <div id="form-errors">
                                        {{form.max_score.errors}}
                                    </div>
                                </p>
                            </div>
                            <div class=col>
                                <p>
                                    <div class="input-group input-group-static mb-4">
                                        <label for="id_cotoff_date"> {% trans "Cutoff date" %} </label>
                                        {{form.cotoff_date}}
                                    </div>
                                    <div id="form-errors">
                                        {{form.cotoff_date.errors}}
                                    </div>
                                </p>
                            </div>
                        </div>
                        <div class=row>
                            <p class="mb-0 ">
                                {% trans "the items of greatest importance in the rating should have the highest percentages. Drivers with indicators close to the permitted limit will have the lowest scores." %}
                            </p>
                        </div>
                        <div class="card">
                            <div class="table-responsive">
                              <table class="table align-items-center mb-0 container">
                                <thead>
                                  <tr>
                                    <th class="text-secondary opacity-7"></th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 align-middle text-center text-sm"> {% trans 'Item to evaluate' %} </th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 align-middle text-center text-sm"> {% trans "points by items" %}  </th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 align-middle text-center text-sm"> {% trans "Maximum infractions in the month" %}</th>
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 align-middle text-center text-sm"> {% trans "Points to subtract for violation" %}</th>
                                  </tr>
                                </thead>
                                <tbody>
                                        {{formset.management_form}}
                                        <div id="form-errors">
                                            {{formset.non_form_errors}}
                                        </div>
                                        {% for form in forms %}
                                        <tr>
                                            <td class="align-middle">
                                                <div class="form-check form-switch ms-5">
                                                    <label class="form-check-label" for="id_item {{forloop.counter0}}"></label>
                                                    <input type="checkbox" name="activate_item" class="form-check-input" onclick="activate(this)" id="id_item {{forloop.counter0}}">
                                                </div>
                                            </td>
                                            <td class="align-middle text-center text-sm">
                                                {{form.0}}
                                            </td>
                                                {% for field in form.1.visible_fields %}
                                                <td class="align-middle text-center text-sm">
                                                        <div class="input-group mb-1">
                                                             {{field.errors}}
                                                            <label for="{{field.id_for_label}}">  </label>
                                                             {{field}}
                                                        </div>
                                                    {% endfor %}
                                                    {% for hidden_field in form.1.hidden_fields %}
                                                            {{hidden_field.errors}}
                                                            {{hidden_field}}
                                                    {% endfor %}
                                                </td>
                                        </tr>
                                       {% endfor %}
                                </tbody>
                              </table>
                            </div>
                          </div>
                        <div class=row>
                            <div class=col>
                                <button class="btn btn-primary mt-3" type="submit"> <i class="fa-solid fa-floppy-disk me-2"></i> {% trans "Save" %} </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'assets/css/estilos_templates.css'%} ">
    </head>


{% endblock %}

{% block scripts %}
<script>
    function activate(id_item) {
        var index = id_item.id
        var it = index[index.length - 1]
        var ddl = document.getElementById("id_itemscoresetup_set-" + it + "-points_item_score");
        var ddl_2 = document.getElementById("id_itemscoresetup_set-" + it + "-maximum_infractions");
        var ddl_3 = document.getElementById("id_itemscoresetup_set-" + it + "-subtract_points");

        if (id_item.checked) {
            ddl.disabled = false;
            ddl_2.disabled = false;
            ddl_3.disabled = false;
        } else {
            ddl.disabled = true;
            ddl.value = 0;
            ddl_2.disabled = true;
            ddl_2.value = 0;
            ddl_3.disabled = true;
            ddl_3.value = 0;
        }
    }

    function update_fields() {
        for (let it = 0; it < 6; it++) {
            var item = document.getElementById("id_item " + it);
            var ddl = document.getElementById("id_itemscoresetup_set-" + it + "-points_item_score");
            var ddl_2 = document.getElementById("id_itemscoresetup_set-" + it + "-maximum_infractions");
            var ddl_3 = document.getElementById("id_itemscoresetup_set-" + it + "-subtract_points");

            if (ddl.value != 0 || ddl_2.value != 0) {
                item.checked = true;
                ddl.disabled = false;
                ddl_2.disabled = false;
                ddl_3.disabled = false;
            }
        }
    }
    update_fields();

</script>
{% endblock scripts %}