apps/checkpoints/urls.py
from django.urls import include, path

from apps.checkpoints.sql import fetch_all_confidatasem

from . import views
from .api import (ExportDataDriver, ExportDataScoreDriver, SearchDataSem,
                  SearchDrivers, SearchScores, events_by_company,
                  events_person_by_company, export_report, user_by_company,
                  vehicles_by_company)

app_name = "checkpoints"

urlpatterns = [
    # Conductores y su manejo
    path(
        "drivers/",
        include(
            [
                path("", views.ListDriverTemplate.as_view(), name="list_drivers"),
                path("add", views.AddDriverView.as_view(), name="add_driver"),
                path(
                    "update/<int:pk>",
                    views.UpdateDriverView.as_view(),
                    name="update_driver",
                ),
                path(
                    "delete/<int:pk>",
                    views.DeleteDriverView.as_view(),
                    name="delete_driver",
                ),
                path(
                    "assign_driver/<int:pk>",
                    views.AddAssignDriverView.as_view(),
                    name="assign_driver",
                ),
                path(
                    "update_assign/<int:pk>",
                    views.UpdateAssignDriverView.as_view(),
                    name="update_assign",
                ),
                path("assign/<int:pk>", views.BottonView.as_view(), name="button_view"),
                path(
                    "update_assing_vehicle/<int:pk>",
                    views.UpdateVehicleAssignView.as_view(),
                    name="update_vehicle_assign",
                ),
                path("drivers-user", SearchDrivers.as_view(), name="user_driver"),
                path("export-drivers", ExportDataDriver.as_view(), name="export_drivers"),
            ]
        ),
    ),
    # Calificación de conductores
    path(
        "driver/",
        include(
            [
                path(
                    "list_score_configuration/",
                    views.ListScoreCompanyTemplate.as_view(),
                    name="list_score_configuration",
                ),
                path(
                    "score_configuration/<int:pk>",
                    views.ScoreConfigurationView.as_view(),
                    name="score_configuration",
                ),
                path("scores-user", SearchScores.as_view(), name="user_scores"),
                path("export-scores", ExportDataScoreDriver.as_view(), name="export_scores"),
            ]
        ),
    ),
    # Reportes
    path(
        "reports/",
        include(
            [
                path("driver", views.ReporDriverView.as_view(), name="report_driver"),
                path("today/", views.ReportTodayView.as_view(), name="report_today"),
                # traer vehicle por compañia
                path(
                    "vehicles-by-company/<int:company_id>/",
                    vehicles_by_company,
                    name="vehicles_by_company",
                ),
                # traer eventos por compañia
                path(
                    "events-by-company/<int:company_id>/",
                    events_by_company,
                    name="events_by_company",
                ),
                path(
                    "events_person-by-company/<int:company_id>/",
                    events_person_by_company,
                    name="events_by_company",
                ),
                path("avldat", export_report, name="avldat"),
                
            ]
        ),
    ),
    path(
        "powerbi/",
        include(
            [
                path(
                    "DataSeM",
                    views.Advanced_AnalyticalView.as_view(),
                    name="DataSeM",
                ),
                path(
                    "Confi_DataSeM",
                    views.DataSemConfigurationList.as_view(),
                    name="Config_DataSeM",
                ),
                path(
                    "DataSeM/Add",
                    views.AddDataSemConfiguration.as_view(),
                    name="AddDataSeM",
                ),
                path(
                    "DataSeM/Update/<int:pk>/",
                    views.UpdateDataSemConfiguration.as_view(),
                    name="UpdateDataSeM",
                ),
                path(
                    "DataSeM/Delete/<int:pk>/",
                    views.DeleteDataSemConfiguration.as_view(),
                    name="DeleteDataSeM",
                ),
                path("search_datasem", SearchDataSem.as_view(), name="search_datasem"),
                path("user_company/<int:company_id>/", user_by_company , name="list_user"),
            ]
        ),
    ),
]

config/urls.py
"""
Configuración de URLs.

La lista `urlpatterns` contiene las direcciones URL de las vistas. Para más detalles, consulte:
https://docs.djangoproject.com/en/4.1/topics/http/urls/
"""

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

apps = i18n_patterns(
    # Módulo personalizado de autenticación de usuarios.
    path("", include("apps.authentication.urls"), name="main"),
    # Métodos de autenticación de Django. El módulo `authentication` los reescribe.
    path("", include("django.contrib.auth.urls")),
    # Módulo de puntos de control (checkpoints).
    path("checkpoints/", include("apps.checkpoints.urls")),
    # Módulo de eventos
    path("events/", include("apps.events.urls")),
    # Módulo de reporte en tiempo real (realtime).
    path("realtime/", include("apps.realtime.urls")),
    # Módulo para la administración, personalización y creación de empresas (whitelabel).
    path("whitelabel/", include("apps.whitelabel.urls")),
    # Modulo de socketmap
    path("socketmap/", include("apps.socketmap.urls")),
    # Modulo de Power BI Embbeded
    path("powerbi/", include("apps.powerbi.urls")),
)

django = i18n_patterns(
    # Sitio de administración de Django.
    path("admin/", admin.site.urls),
    # Librería de control de traducciones
    path("rosetta/", include("rosetta.urls")),
)


media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

static_files = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns = apps + django + media + static_files

apps/checkpoints/models.py
""" Modelos asociados al módulo puntos de control.

Este módulo crea los modelos para los puntos de control, las rutas, el control de fatiga y los
datos para análisis de los conductores.

Para una mayor referencia sobre la creación de modelos en Django, consulte
https://docs.djangoproject.com/en/4.1/topics/db/models/
"""

from django.db import models
from django.utils.translation import gettext_lazy as _


class Driver(models.Model):
    """
    Modelo de la tabla driver. Almacena la información asociada a cada conductor
    de la empresa cliente.
    """

    company = models.ForeignKey(
        "whitelabel.Company",
        on_delete=models.CASCADE,
        verbose_name=_("company"),
        default=1,
    )
    last_update = models.DateTimeField(
        verbose_name=_("last update"),
        auto_now=True,
    )
    personal_identification_number = models.PositiveBigIntegerField(
        verbose_name=_("personal ID"),
        null=False,
        blank=False,
    )
    first_name = models.CharField(
        max_length=30,
        verbose_name=_("first name"),
        default="",
    )
    last_name = models.CharField(
        max_length=30,
        verbose_name=_("last name"),
        default="",
    )
    address = models.CharField(
        max_length=30,
        verbose_name=_("address"),
        default="",
        blank=True,
    )
    phone_number = models.PositiveBigIntegerField(
        verbose_name=_("movil number"),
        default="",
    )
    password = models.CharField(
        max_length=10,
        verbose_name=_("password"),
        default="",
        null=True,
    )
    date_joined = models.DateField(verbose_name=_("date joined"))
    is_active = models.BooleanField(default=False, verbose_name=_("Active"))
    visible = models.BooleanField(default=True, verbose_name=_("visible"))
    modified_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("modified by"),
        related_name="modified_driver",
        null=True,
    )

    created_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("created by"),
        related_name="created_driver",
        null=True,
    )

    def __str__(self):
        return f"{self.first_name}   {self.last_name}"


class DriverAnalytic(models.Model):
    """
    Modelo de la tabla driver_analytic. Almacena la información asociada a la asignación
    y desasignación de conductores a vehiculos.
    """

    vehicle = models.ForeignKey(
        "realtime.Vehicle",
        on_delete=models.CASCADE,
        verbose_name=_("vehicle"),
        null=True,
    )
    driver = models.ForeignKey(
        "Driver", on_delete=models.CASCADE, verbose_name=_("driver"), null=True
    )
    date_joined = models.DateTimeField(
        verbose_name=_("date joined"),
        null=True,
    )
    date_leaving = models.DateTimeField(
        verbose_name=_("date leaving"),
        blank=True,
        null=True,
    )
    modified_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("modified by"),
        related_name="modified_driver_analytic",
        null=True,
    )
    created_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("created by"),
        related_name="created_driver_analytic",
        null=True,
    )
    last_update = models.DateTimeField(
        verbose_name=_("last update"),
        auto_now=True,
    )

    def __str__(self):
        return f"{self.vehicle} --> Driver: {self.driver}"


class ItemScore(models.Model):
    """
    Modelo de la tabla item_score. Almacena los items predefinidos sobre los cuales
    se califica a los conductores.
    """

    item = models.CharField(
        verbose_name=_("item"),
        max_length=50,
    )
    modified_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("modified by"),
        related_name="modified_items",
        null=True,
    )
    created_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("created by"),
        related_name="created_items",
        null=True,
    )
    last_updated = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("last updated"),
        null=True,
    )

    def __str__(self):
        return f"{self.item}"


class CompanyScoreSetup(models.Model):
    """
    Modelo de la tabla company_score_setup Almacena el puntaje que cada empresa
    establece para calificar a sus conductores.
    """

    company = models.ForeignKey(
        "whitelabel.Company",
        on_delete=models.CASCADE,
        verbose_name=_("company"),
        null=True,
    )
    min_score = models.FloatField(
        verbose_name=_("minimum score"),
        blank=True,
        default=0,
    )
    max_score = models.FloatField(
        verbose_name=_("maximum score"),
        blank=True,
        default=0,
    )
    cotoff_date = models.IntegerField(
        verbose_name=_("cutoff date"),
        default=1,
        choices=[(day, day) for day in range(1, 31)],
    )
    modified_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("modified by"),
        related_name="modified_Companyscoresetup",
        null=True,
    )
    created_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("created by"),
        related_name="created_companyscoresetup",
        null=True,
    )
    last_update = models.DateTimeField(
        verbose_name=_("last update"),
        auto_now=True,
    )

    def __str__(self):
        return f" {self.company} --> Score: [ {self.min_score} , {self.max_score},{self.cotoff_date}]"


class ItemScoreSetup(models.Model):
    """
    Modelo de la tabla item_score_setup. Almacena el porcentaje que representa en la nota total
    cada item a evaluar.
    """

    item = models.ForeignKey(
        "ItemScore",
        on_delete=models.CASCADE,
        verbose_name=_("item"),
        default=1,
    )
    company_score = models.ForeignKey(
        "CompanyScoreSetup",
        on_delete=models.CASCADE,
        verbose_name=_("company score"),
        null=True,
    )
    points_item_score = models.FloatField(
        verbose_name=_("points score item"),
        blank=True,
        default=0,
    )
    maximum_infractions = models.IntegerField(
        verbose_name=_("maximum infractions"),
        blank=True,
        default=0,
    )
    subtract_points = models.FloatField(
        verbose_name=_("subtract points"),
        blank=True,
        default=0,
    )
    modified_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("modified by"),
        related_name="modified_itemsscoresetup",
        null=True,
    )
    created_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("created by"),
        related_name="created_itemsscoresetup",
        null=True,
    )
    last_update = models.DateTimeField(
        verbose_name=_("last update"),
        auto_now=True,
    )

    def __str__(self):
        return f" {self.company_score}---{self.item} --> Percentage:[ {self.points_item_score}] -- "


class FatigueControl(models.Model):

    """
    Modelo de el cual realiza el calculo de la calificacion del conductor con el modelo DriverAnalytic
    de acuerdo a los parametros que se hayan establecido en el modelo ItemScoreSetup y se valida
    de acuerdo a la información que envie el divice al modelo Avldata
    """

    driver = models.ForeignKey(
        "DriverAnalytic", on_delete=models.CASCADE, verbose_name=_("Driver"), null=True
    )
    items_score = models.ForeignKey(
        "ItemScoreSetup",
        on_delete=models.CASCADE,
        verbose_name=_("Items_score"),
        null=True,
    )
    avl_data = models.ForeignKey(
        "realtime.AVLData",
        on_delete=models.CASCADE,
        verbose_name=_("AVLData"),
        null=True,
    )
    vehicle = models.ForeignKey(
        "realtime.Vehicle",
        on_delete=models.CASCADE,
        verbose_name=_("Vehicle"),
        default=None,
    )

    def __str__(self):
        return f" {self.driver} --> {self.items_score} --> {self.avl_data}"


class Report(models.Model):
    # No necesitas definir permisos en la clase Meta para los permisos básicos
    class Meta:
        verbose_name_plural = "reports"


class Advanced_Analytical(models.Model):
    user = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("user"),
        null=True,
    )
    id_workspace = models.CharField(
        max_length=50,
        verbose_name=_("ID Workspace"),
    )

    id_report = models.CharField(
        max_length=30,
        verbose_name=_("id_report"),
    )
    workspace = models.CharField(
        max_length=30,
        verbose_name=_("workspace"),
    )
    report = models.CharField(
        max_length=30,
        verbose_name=_("report"),
    )

    coin = models.ForeignKey(
        "whitelabel.Coin",
        on_delete=models.CASCADE,
        verbose_name=_("coin"),
        null=True,
    )
    price = models.DecimalField(
        max_digits=10,  # Ajusta estos valores según tus necesidades
        decimal_places=2,  # Ajusta estos valores según tus necesidades
        verbose_name=_("price"),
        blank=True,
        null=True,
    )
    modified_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("modified by"),
        related_name="modified_advanced_analytic",
        null=True,
    )
    created_by = models.ForeignKey(
        "authentication.User",
        on_delete=models.CASCADE,
        verbose_name=_("created by"),

apps/templates/checkpoints/driver/add_driver.html
{% load i18n static %}
{% block content %}
{{form.media}}
{% load i18n static %}
    <div class="modal-content" id="miModal" style="z-index: 1050">
        <div class="modal-body">
            <div class="card">
                <div class="modal-header">
                <h3> {% trans "Add Driver" %} </h3>
                <button type="button" id="cerrarVenta" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="card-body">
                <form hx-post="{{ request.path }}" hx-target="#modal-content" > {% csrf_token %}
                        <div class="input-group input-group-static mb-4">
                            <label for="id_company"> {% trans "Company:" %} <span style="color:red;">*</span> </label>
                            {{form.company}}
                        </div>
                        <div id="form-errors">
                            {{form.company.errors}}
                        </div>
                    <div class="row">
                        <div class="col">
                                <div class="input-group input-group-static mb-4">
                                    <label for="id_personal_identification_number"> {% trans "Personal ID:" %} <span style="color:red;">*</span> </label>
                                    {{form.personal_identification_number}}
                                </div>
                                <div id="form-errors">
                                    {{form.personal_identification_number.errors}}
                                </div>

                        </div>

                        <div class="col">
                                <div class="input-group input-group-static mb-4">
                                    <label for="id_first_name"> {% trans "First name:" %} <span style="color:red;">*</span> </label>
                                    {{form.first_name}}
                                </div>
                        </div>

                        <div class="col">
                                <div class="input-group input-group-static mb-4">
                                    <label for="id_last_name"> {% trans "Last name:" %} <span style="color:red;">*</span> </label>
                                    {{form.last_name}}
                                </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                                <div class="input-group input-group-static mb-4">
                                    <label for="id_phone_number"> {% trans "Movil number:" %} <span style="color:red;">*</span> </label>
                                    {{form.phone_number}}
                                </div>
                        </div>
                        <div class="col">
                                <div class="input-group input-group-static mb-4">
                                    <label for="id_address"> {% trans "Address:" %} </label>
                                    {{form.address}}
                                </div>
                        </div>
                        <div class="col">
                                <div class="input-group input-group-static mb-4">
                                    <label for="id_password"> {% trans "Password:" %}</span> </label>
                                    {{form.password}}
                                </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-check form-switch" style="padding-block-start: 35px;">
                                <label for="id_is_active" class="form-check-label"> {% trans "Is active?" %} </label>
                                {{form.is_active}}
                            </div>
                        </div>

                        <div class="col">
                                <div class="input-group input-group-static mt-3">
                                    <label for="id_date_joined"> {% trans "Date joined:" %} <span style="color:red;">*</span> </label>
                                    <input type="date" name="date_joined" class="form-control" required id="id_date_joined" value="{{form.date_joined.value | date:'c'}}">
                                </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <button class="btn btn-primary mt-3" type="submit"> <i class="fa-solid fa-floppy-disk me-2"></i> {% trans "Save" %} </button>
                        </div>
                        <head>
                            <link rel="stylesheet" type="text/css" href="{% static 'assets/css/estilos_templates.css' %}" />
                            <link rel="stylesheet" type="text/css" href="{% static 'assets/css/select2.css' %}" />
                        </head>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
<!-- Incluir jQuery primero -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- Incluir Select2 después de jQuery -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="{% static 'assets\js\checkpoints\driver\select.js' %}"></script>

<style>
    .select2-container--default .select2-results__option--highlighted.select2-results__option--selectable {
        background-color: {{ button_color }};
        color: white;
    }
  </style>
{% endblock %}

apps/templates/checkpoints/driver/delete_driver.html
{% load i18n static %} {% block content %}

<!-- Un formulario que pregunta al usuario si está seguro de querer eliminar el conductor. -->
<div class="modal-content">
  <div class="row">
    <div class="modal-body-md-1">
      <div class="col" >
        <div class="card align-items-center">
          <div class="card-body">
            <form hx-post="{{ request.path }}" hx-target="#modal-content">
              {% csrf_token %}
              <p>{% trans '¿Are you sure you want to delete the Driver' %} "{{ object.first_name}} {{object.last_name}}"?</p>
              <div class="d-grid col-4 mx-auto">
                <button type="submit" class="btn btn-primary">{% trans "Confirm" %}</button>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">{% trans 'Cancel' %}</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

apps/templates/checkpoints/driver/update_driver.html
{% load i18n static %}
{% block content %}
{{form.media}}
{% load i18n static %}
<div class="modal-content" id="miModal" style="z-index: 1050">
            <div class="modal-body">
                <div class="card">
                    <div class="modal-header">
                    <h3 class="">{% trans "Edit Driver" %}</h3>
                    <button type="button" id="cerrarVenta" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="card-body">
                    <form hx-post="{{ request.path }}" hx-target="#modal-content" > {% csrf_token %}
                            <div class="input-group input-group-static mb-4">
                                <label for="id_company"> {% trans "Company:" %} <span style="color:red;">*</span> </label>
                                {{form.company}}
                            </div>
                            <div id="form-errors">
                                {{form.company.errors}}
                            </div>
                        <div class="row">
                            <div class="col">
                                    <div class="input-group input-group-static mb-4">
                                        <label for="id_personal_identification_number"> {% trans "Personal ID:" %} <span style="color:red;">*</span> </label>
                                        {{form.personal_identification_number}}
                                    </div>
                                    <div id="form-errors">
                                        {{form.personal_identification_number.errors}}
                                    </div>

                            </div>

                            <div class="col">
                                    <div class="input-group input-group-static mb-4">
                                        <label for="id_first_name"> {% trans "First name:" %} <span style="color:red;">*</span> </label>
                                        {{form.first_name}}
                                    </div>
                            </div>

                            <div class="col">
                                    <div class="input-group input-group-static mb-4">
                                        <label for="id_last_name"> {% trans "Last name:" %} <span style="color:red;">*</span> </label>
                                        {{form.last_name}}
                                    </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                    <div class="input-group input-group-static mb-4">
                                        <label for="id_phone_number"> {% trans "Movil number:" %} <span style="color:red;">*</span> </label>
                                        {{form.phone_number}}
                                    </div>
                            </div>
                            <div class="col">
                                    <div class="input-group input-group-static mb-4">
                                        <label for="id_address"> {% trans "Address:" %} </label>
                                        {{form.address}}
                                    </div>
                            </div>
                            <div class="col">
                                    <div class="input-group input-group-static mb-4">
                                        <label for="id_password"> {% trans "Password:" %}</span> </label>
                                        {{form.password}}
                                    </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-check form-switch" style="padding-block-start: 35px;">
                                    <label for="id_is_active" class="form-check-label"> {% trans "Is active?" %} </label>
                                    {{form.is_active}}
                                </div>
                            </div>

                            <div class="col">
                                    <div class="input-group input-group-static mt-3">
                                        <label for="id_date_joined"> {% trans "Date joined:" %} <span style="color:red;">*</span> </label>
                                        <input type="date" name="date_joined" class="form-control" required id="id_date_joined" value="{{form.date_joined.value | date:'c'}}">
                                    </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <button class="btn btn-primary mt-3" type="submit"> <i class="fa-solid fa-floppy-disk me-2"></i> {% trans "Save" %} </button>
                            </div>
                            <head>
                                <link rel="stylesheet" type="text/css" href="{% static 'assets/css/estilos_templates.css' %}" />
                                <link rel="stylesheet" type="text/css" href="{% static 'assets/css/select2.css' %}" />
                            </head>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock content %}
    {% block scripts %}
    <!-- Incluir jQuery primero -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Incluir Select2 después de jQuery -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="{% static 'assets\js\checkpoints\driver\select.js' %}"></script>

    <style>
        .select2-container--default .select2-results__option--highlighted.select2-results__option--selectable {
            background-color: {{ button_color }};
            color: white;
        }
      </style>
    {% endblock %}